/*
EonaCat DeepSpeak
Copyright (C) 2025 EonaCat (Jeroen Saey)

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://EonaCat.com/License

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License

*/

namespace EonaCat.DeepSpeak.Models;

/// <summary>
/// Chat response
/// </summary>
public class ChatResponse
{
    /// <summary>
    /// The unique identifier for the conversation.
    /// </summary>
    public string? Id { get; set; }

    /// <summary>
    /// A list of choices generated by the model for the completion.
    /// </summary>
    public List<Choice> Choices { get; set; } = [];

    /// <summary>
    /// The name of the model used to generate the completion.
    /// </summary>
    public string? Model { get; set; }

    /// <summary>
    /// The Unix timestamp (in seconds) when the chat completion was created.
    /// </summary>
    public long Created { get; set; }

    /// <summary>
    /// The type of object, which is "chat.completion".
    /// </summary>
    public string Object { get; set; } = "chat.completion";

    /// <summary>
    /// Usage information for the chat completion request.
    /// </summary>
    public Usage? Usage { get; set; }
}